Added more clear SSH error message for improper credentials
carsdotcom/cars-forge pull request #31
Opened 2022-10-12 16:58 UTC by Macr0Nerd

Rather than an obscure SSH error, this will tell you when you lack the proper credentials to connect (usually an AMI or user-data error).

2022-10-12 17:06 UTC, jagmoreira requested changes

2022-10-12 17:06 UTC, jagmoreira commented on CHANGELOG.md
> +- **Forge** - Added error to show when SSH credentials are invalid
This line should be in the top of the Changed section in `Unreleased`

2022-10-12 18:32 UTC, jagmoreira submitted a review, later dismissed

2022-10-13 19:27 UTC, npatel-cars commented on src/forge/ssh.py
> +                logger.error('Missing proper SSH credentials to connect. Please check your user_data and AMI.')
'user_data or AMI."?

2022-10-13 22:44 UTC, Macr0Nerd commented on src/forge/ssh.py
> +                logger.error('Missing proper SSH credentials to connect. Please check your user_data and AMI.')
I think and/or might be a bit better

2022-10-17 13:22 UTC, jagmoreira approved these changes

2022-10-17 13:38 UTC, npatel-cars approved these changes

2022-10-17 14:03 UTC, merged